---
- name: dnf_clean
  command: dnf clean all

- name: Removing_Some_Container_Pkgs
  dnf:
    name:
      - podman
      - buildah
    state: absent

- name: Print-Msg
  debug:
    var: HelloMsg.stdout_lines

- name: PrintVersion
  debug:
    var: VersionMsg.stdout_lines
