---
- name: dnf_clean
  command: dnf clean all
  
- name: Disable the built-in PostgreSQL module
  command: sudo dnf -qy module disable postgresql

- name: initialize the database
  command: /usr/pgsql-14/bin/postgresql-14-setup initdb

- name: Reload The Postgres Service
  ansible.builtin.systemd:
    name: postgresql-14
    state: reloaded
  